#!/bin/bash

[ -z "$ALICE_PHYSICS" ] && echo "AliPhysics environment required! Load it before sourcing this." && return

HYPERML_DATA="$PWD/Data"
HYPERML_FIGURES="$PWD/Figures"
HYPERML_RESULTS="$PWD/Results"
HYPERML_MODELS="$PWD/Models"
HYPERML_CODE="$PWD"
HYPERML_COMMON="$HYPERML_CODE/common"

export PYTHONPATH="${PYTHONPATH}:$HYPERML_COMMON/TrainingAndTesting:$HYPERML_COMMON/Utils"

export HYPERML_DATA="$HYPERML_DATA"
export HYPERML_FIGURES="$HYPERML_FIGURES"
export HYPERML_MODELS="$HYPERML_MODELS"
export HYPERML_RESULTS="$HYPERML_RESULTS"
export HYPERML_EFFICIENCIES="$HYPERML_RESULTS/Efficiencies"

[ ! -d "$HYPERML_DATA" ] && mkdir -p $HYPERML_DATA
[ ! -d "$HYPERML_FIGURES" ] && mkdir -p $HYPERML_FIGURES
[ ! -d "$HYPERML_MODELS" ] && mkdir -p $HYPERML_MODELS
[ ! -d "$HYPERML_EFFICIENCIES" ] && mkdir -p $HYPERML_EFFICIENCIES
[ ! -d "$HYPERML_RESULTS" ] && mkdir -p $HYPERML_RESULTS