NBODY: 2
FILE_PREFIX: K0S_L10_E40_analysis
PDG: 310
EINT: 40
MULTIPLICITY: 39.15
BRATIO: 0.692
T: 0.22745
SIGMA: 0.003
MASS_WINDOW: 0.04
#PT_BINS: [0,0.0625,0.125,0.1875,0.25,0.3125,0.375,0.4375,0.5,0.5625,0.625,0.6875,0.75,0.8125,0.875,0.9375,1.0,1.125,1.25,1.375,1.5,1.625,1.75,1.875,2.0,2.125,2.25,2.375,2.5,2.625,2.75,2.875, 3.0]
PT_BINS: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.2,1.4,1.6,1.8,2.0,2.25,2.5,2.75, 3.0]
#PT_BINS: [0, 3.0]
BKG_MODELS:
- expo
- pol1
- pol2
BDT_EFFICIENCY:
- 0.9
- 1.0
- 0.001
MC_PATH: ../Data/K0S_L10_E40/fntSig_L10_E40_train.root
BKG_PATH: ../Data/K0S_L10_E40/fntBkg_L10_E40_train.root
DATA_PATH:
- ../Data/K0S_L10_E40/fntBkg_L10_E40_data.root
EVENT_PATH:
- ../Data/K0S_L10_E40/merged_ev.root

PRESELECTION: cosp > 0.999999 and pt<3
STD_SELECTION: pt<1 and cosp>0.9999
GAUSS: true
XGBOOST_PARAMS:
  silent: 1
  n_jobs: 8
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist
HYPERPARAMS:
  max_depth: 7
  learning_rate: 0.167
  n_estimators: 84
  gamma: 0.525
  min_child_weight: 9.82
  subsample: 0.89
  colsample_bytree: 0.64
  seed: 42
HYPERPARAMS_RANGE:
  max_depth:
  - 5
  - 20
  learning_rate:
  - 0.01
  - 0.3
  n_estimators:
  - 50
  - 500
  gamma:
  - 0.3
  - 1.1
  min_child_weight:
  - 1
  - 12
  subsample:
  - 0.5
  - 0.9
  colsample_bytree:
  - 0.5
  - 0.9
TRAINING_COLUMNS:
- cosp
- dist
- dca
- d0prod
- rapidity
