BDT_EFFICIENCY:
- 0.8
- 0.99
- 0.01
BKG_MODELS:
- pol1
BKG_PATH: /home/giacomo/StrangeNA60plusML/Data/K0S_L5_E40/fntBkg_K0S_E40_train.root
BRATIO: 0.692
DATA_PATH: /home/giacomo/StrangeNA60plusML/Data/K0S_L5_E40/fntBkg_K0S_E40_data.root
EFF_RANGE_SYST:
- 0.02
- 0.02
EINT: 40
FILE_PREFIX: K0S_L5_E40_analysis
FIT_PATH: /home/giacomo/StrangeNA60plusML/Data/K0S_L5_E40/fntSig_K0S_E40_train.root
HYPERPARAMS:
  colsample_bytree: 0.64
  gamma: 0.525
  learning_rate: 0.167
  max_depth: 7
  min_child_weight: 9.82
  n_estimators: 83
  seed: 42
  subsample: 0.89
HYPERPARAMS_RANGE:
  colsample_bytree:
  - 0.5
  - 0.9
  gamma:
  - 0.3
  - 1.1
  learning_rate:
  - 0.01
  - 0.3
  max_depth:
  - 5
  - 20
  min_child_weight:
  - 1
  - 12
  n_estimators:
  - 50
  - 500
  subsample:
  - 0.5
  - 0.9
INFO_PATH: /home/giacomo/StrangeNA60plusML/Data/K0S_L5_E40/Bkg-histos_K0S_E40_data.root
MASS_WINDOW: 0.05
MC_PATH: /home/giacomo/StrangeNA60plusML/Data/K0S_L5_E40/fntSig_K0S_E40_train.root
MULTIPLICITY: 39.15
NBINS: 75
NEVENTS: 19468956.0
PDG: 310
PRESELECTION: cosp > 0.9994 and pt < 3 and arm > -0.83 and arm < 0.83
PT_BINS:
- 0
- 3.0
SIGMA: 0.003
SIG_MODELS:
- d-gauss
STD_SELECTION: dist > 0.2 and cosp > 0.99999 and (d0prod < -0.00002 or d0prod > 0.00002)
  and dca < 0.003 and arm > -0.84 and arm < 0.84
T: 0.22745
TRAINING_COLUMNS:
- cosp
- dist
- dca
- d0prod
- rapidity
XGBOOST_PARAMS:
  eval_metric: auc
  n_jobs: 8
  objective: binary:logistic
  random_state: 42
  silent: 1
  tree_method: hist
