FILE_PREFIX: 'LAMBDA_L5_E40_analysis'

PDG: 3122
EINT: 40
MULTIPLICITY: 43.1
BRATIO: 0.639
T: 0.258
SIGMA: 0.001
MASS_WINDOW: 0.015
NBINS: 60
PT_BINS: [0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.,1.2,1.4,1.6,1.8,2.0,2.25,2.5,2.75, 3.0,3.25,3.5,3.75]
NEVENTS: 9000000

SIG_MODELS: ['d-gauss','kde']
BKG_MODELS: ['pol1', 'pol2']

EFF_RANGE_SYST: [0.05, 0.05]

BDT_EFFICIENCY: [0.60, 1., 0.01] ##min, max ,step

MC_PATH: /media/giacomo/Volume/LAMBDA_L5_E40/fntSig_LAMBDA_L5_E40.root
BKG_PATH: /media/giacomo/Volume/LAMBDA_L5_E40/fntBkg_LAMBDA_L5_E40_train.root
DATA_PATH: /media/giacomo/Volume/LAMBDA_L5_E40/fntBkg_LAMBDA_L5_E40.root

PRESELECTION: pt<3.75 and cosp > 0.9999
STD_SELECTION: pt<3 and dist > 5 and cosp > 0.999988 and dcaD < 0.007 and dca<0.015 and cospD > 0.999


XGBOOST_PARAMS:
  # general parameters
  silent: 1 # print message (useful to understand whats happening)
  n_jobs: 8 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist

HYPERPARAMS:
  max_depth: 7
  learning_rate: 0.167
  n_estimators: 83
  gamma: 0.525
  min_child_weight: 9.82
  subsample: 0.89
  colsample_bytree: 0.64
  seed : 42

HYPERPARAMS_RANGE: #TODO: check if it works without tuples
  # booster parameters
  max_depth: !!python/tuple [5, 20] # defines the maLAMBDAmum depth of a single tree (regularization)
  learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  n_estimators: !!python/tuple [50, 500] # number of boosting trees
  gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  min_child_weight: !!python/tuple [1, 12]
  subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree
  # # lambda: (0,10]  # L2 regularization term on weights
  # # alpha: (0,10]  # L1 regularization term on weight

TRAINING_COLUMNS: 
  - cosp
  - dist
  - dca
  - d0prod
  - rapidity