BDT_EFFICIENCY:
- 0.8
- 1.0
- 0.01
BKG_MODELS:
- pol1
- pol2
BKG_PATH: /home/giacomo/StrangeNA60plusML/Data/LAMBDA_L5_E40/fntBkg_LAMBDA_E40_train.root
BRATIO: 0.639
DATA_PATH: /home/giacomo/StrangeNA60plusML/Data/LAMBDA_L5_E40/fntBkg_LAMBDA_E40_data.root
EFF_RANGE_SYST:
- 0.02
- 0.02
EINT: 40
FILE_PREFIX: LAMBDA_L5_E40_analysis
FIT_PATH: /home/giacomo/StrangeNA60plusML/Data/LAMBDA_L5_E40/fntSig_LAMBDA_E40_train.root
HYPERPARAMS:
  colsample_bytree: 0.64
  gamma: 0.525
  max_depth: 7
  min_child_weight: 9.82
  n_estimators: 83
  seed: 42
  subsample: 0.89
HYPERPARAMS_RANGE:
  colsample_bytree:
  - 0.5
  - 0.9
  gamma:
  - 0.3
  - 1.1
  learning_rate:
  - 0.01
  - 0.3
  max_depth:
  - 5
  - 20
  min_child_weight:
  - 1
  - 12
  n_estimators:
  - 50
  - 500
  subsample:
  - 0.5
  - 0.9
INFO_PATH: /home/giacomo/StrangeNA60plusML/Data/LAMBDA_L5_E40/Bkg-histos_LAMBDA_E40_data.root
MASS_WINDOW: 0.02
MC_PATH: /home/giacomo/StrangeNA60plusML/Data/LAMBDA_L5_E40/fntSig_LAMBDA_E40_train.root
MULTIPLICITY: 43.1
NBINS: 80
NEVENTS: 19468956.0
PDG: 3122
PRESELECTION: pt<3 and cosp > 0.9998
PT_BINS:
- 0
- 10
SIGMA: 0.001
SIG_MODELS:
- d-gauss
STD_SELECTION: pt<3 and dist > 5 and cosp > 0.999988 and dcaD < 0.007 and dca<0.015
  and cospD > 0.999
T: 0.258
TRAINING_COLUMNS:
- cosp
- dist
- dca
- d0prod
- rapidity
XGBOOST_PARAMS:
  eval_metric: auc
  n_jobs: 8
  objective: binary:logistic
  random_state: 42
  silent: 1
  tree_method: hist
