BDT_EFFICIENCY:
- 0.01
- 1.0
- 0.01
BKG_MODELS:
- pol1
BKG_PATH: /home/giacomo/StrangeNA60plusML/Data/OMEGA_L5_E40/fntBkg_OMEGA_E40_train.root
BRATIO: 0.433
DATA_PATH: /home/giacomo/StrangeNA60plusML/Data/OMEGA_L5_E40/fntBkg_OMEGA_E40_data.root
EFF_RANGE_SYST:
- 0.05
- 0.05
EINT: 40
FILE_PREFIX: OMEGA_L5_E40_analysis
FIT_PATH: /home/giacomo/StrangeNA60plusML/Data/OMEGA_L5_E40/fntSig_OMEGA_E40_train.root
HYPERPARAMS:
  colsample_bytree: 0.64
  gamma: 0.525
  learning_rate: 0.167
  max_depth: 7
  min_child_weight: 9.82
  n_estimators: 83
  seed: 42
  subsample: 0.89
HYPERPARAMS_RANGE:
  colsample_bytree:
  - 0.5
  - 0.9
  gamma:
  - 0.3
  - 1.1
  learning_rate:
  - 0.01
  - 0.3
  max_depth:
  - 5
  - 20
  min_child_weight:
  - 1
  - 12
  n_estimators:
  - 50
  - 500
  subsample:
  - 0.5
  - 0.9
INFO_PATH: /home/giacomo/StrangeNA60plusML/Data/OMEGA_L5_E40/Bkg-histos_OMEGA_E40_data.root
MASS_WINDOW: 0.03
MC_PATH: /home/giacomo/StrangeNA60plusML/Data/OMEGA_L5_E40/fntSig_OMEGA_E40_train.root
MULTIPLICITY: 0.14
NBINS: 80
NEVENTS: 19718956.0
PDG: 3334
PRESELECTION: pt < 10 and cosp > 0.99999 and mD < 1.117 and mD > 1.1145 and dcaD <
  0.002 and dca < 0.003 and distD > 0.2 and m > 1.6223 and m < 1.7226
PT_BINS:
- 0
- 10
SIGMA: 0.002
SIG_MODELS:
- gauss
STD_SELECTION: (bxyD < -0.0032 or bxyD > 0.0032) and (bxy < -0.0008 or bxy > 0.0008)
  and mD < 1.117 and mD > 1.1145 and rapidity < 2.55 and dcaD < 0.0016 and cospD >
  0.999997 and distD > 0.31 and dist > 0.14  and distD > 0.2 and dca < 0.0023 and
  cosp > 0.999998 and pt > 0.9
T: 0.218
TRAINING_COLUMNS:
- cospD
- bxyD
- bxy
- dist
- rapidity
XGBOOST_PARAMS:
  eval_metric: auc
  n_jobs: 8
  objective: binary:logistic
  random_state: 42
  silent: 1
  tree_method: hist
