NBODY: 2
FILE_PREFIX: 'PHI_L5_E158_analysis'

PDG: 333
EINT: 158
MULTIPLICITY: 8.46
BRATIO: 0.489
T: 0.298
SIGMA: 0.003

PT_BINS: [2., 3.]

BKG_MODELS: ['expo', 'pol1', 'pol2']

BDT_EFFICIENCY: [0.01, 1.0, 0.01] ##min, max ,step

MC_PATH: ../Data/PHI_L5_E158/fntSig_PHI_L5_E158_TS.root
BKG_PATH: ../Data/PHI_L5_E158/fntBkg_PHI_L5_E158_TS.root
DATA_PATH: ['../Data/PHI_L5_E158/fntBkg_PHI_Full_L5_E158_Data.root']
EVENT_PATH: ['../Data/PHI_L5_E158/Bkg-histos_PHI_L5_E158_Data.root']

PRESELECTION: dist < 1.4 and d0prod < 0.09 and d0prod > -0.09 and dca < 0.016 and thetad > 0.97  and arm < 0.3 and arm > -0.3

LARGE_DATA: True
GAUSS: False

XGBOOST_PARAMS:
  # general parameters
  silent: 1 # print message (useful to understand whats happening)
  n_jobs: 8 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist

HYPERPARAMS:
  #max_depth: 7
  #learning_rate: 0.167
  #n_estimators: 83
  #gamma: 0.525
  #min_child_weight: 9.82
  #subsample: 0.89
  #colsample_bytree: 0.64
  seed : 42
  max_depth: 8
  learning_rate: 0.186
  n_estimators: 477
  gamma: 0.337
  min_child_weight: 1.71
  subsample: 0.89
  colsample_bytree: 0.74

HYPERPARAMS_RANGE: #TODO: check if it works without tuples
  # booster parameters
  max_depth: !!python/tuple [5, 20] # defines the maximum depth of a single tree (regularization)
  learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  n_estimators: !!python/tuple [50, 500] # number of boosting trees
  gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  min_child_weight: !!python/tuple [1, 12]
  subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree
  # # lambda: (0,10]  # L2 regularization term on weights
  # # alpha: (0,10]  # L1 regularization term on weight

TRAINING_COLUMNS: 
  - cosp
  - dist
  - dca
  - d0prod
  - d01 
  - d02
  - ptMin
  #- thetad
  - rapidity
