BDT_EFFICIENCY:
- 0.7
- 1.0
- 0.01
BKG_MODELS:
- pol1
BKG_PATH: /home/giacomo/StrangeNA60plusML/Data/XI_L5_E40/fntBkg_XI_E40_train.root
BRATIO: 0.638
DATA_PATH: /home/giacomo/StrangeNA60plusML/Data/XI_L5_E40/fntBkg_XI_E40_data.root
EFF_RANGE_SYST:
- 0.05
- 0.05
EINT: 40
FILE_PREFIX: XI_L5_E40_analysis
FIT_PATH: /home/giacomo/StrangeNA60plusML/Data/XI_L5_E40/fntSig_XI_E40_train.root
HYPERPARAMS:
  colsample_bytree: 0.64
  gamma: 0.525
  learning_rate: 0.167
  max_depth: 7
  min_child_weight: 9.82
  n_estimators: 83
  seed: 42
  subsample: 0.89
HYPERPARAMS_RANGE:
  colsample_bytree:
  - 0.5
  - 0.9
  gamma:
  - 0.3
  - 1.1
  learning_rate:
  - 0.01
  - 0.3
  max_depth:
  - 5
  - 20
  min_child_weight:
  - 1
  - 12
  n_estimators:
  - 50
  - 500
  subsample:
  - 0.5
  - 0.9
INFO_PATH: /home/giacomo/StrangeNA60plusML/Data/XI_L5_E40/Bkg-histos_XI_E40_data.root
MASS_WINDOW: 0.018
MC_PATH: /home/giacomo/StrangeNA60plusML/Data/XI_L5_E40/fntSig_XI_E40_train.root
MULTIPLICITY: 2.96
NBINS: 35
NEVENTS: 4963600.0
NEVENTS_DATA: 19468956.0
PDG: 3312
PRESELECTION: cosp > 0.9995 and imp1 > 0.01 and imp2 > 0.01 and imp0 > 0.01
PT_BINS:
- 0
- 0.2
- 0.4
- 0.6
- 0.8
- 1.0
- 1.2
- 1.4
- 1.6
- 1.8
- 2.0
- 2.5
SIGMA: 0.0022
SIG_MODELS:
- d-gauss
STD_SELECTION: pt<3 and dist > 5 and cosp > 0.999988 and dcaD < 0.007 and dca<0.015
  and cospD > 0.999
T: 0.222
TRAINING_COLUMNS:
- cosp
- bxy
- bxyD
- dca
- dcaD
- dist

XGBOOST_PARAMS:
  eval_metric: auc
  n_jobs: 8
  objective: binary:logistic
  random_state: 42
  silent: 1
  tree_method: hist
