FILE_PREFIX: 'XI_L5_E40_analysis'

PDG: 3312
EINT: 40
MULTIPLICITY: 2.96
BRATIO: 0.638
T: 0.222
SIGMA: 0.0008
MASS_WINDOW: 0.012
NBINS: 35
PT_BINS: [0.,0.5,0.8,1.,1.25,1.5, 2.5]
NEVENTS: 9000000

SIG_MODELS: ['d-gauss']
BKG_MODELS: ['pol1', 'expo']

EFF_RANGE_SYST: [0.05, 0.05]

BDT_EFFICIENCY: [0.70, 1., 0.01] ##min, max ,step

MC_PATH: /media/giacomo/Volume/ML_DATA/XI_L5_E40/fntSig_XI_L5_E40.root
BKG_PATH: /media/giacomo/Volume/ML_DATA/XI_L5_E40/fntBkg_XI_L5_E40_train.root
DATA_PATH: /media/giacomo/Volume/ML_DATA/XI_L5_E40/fntBkg_XI_L5_E40.root

PRESELECTION: cosp > 0.9999 and pt<2.5
STD_SELECTION: pt<3 and dist > 5 and cosp > 0.999988 and dcaD < 0.007 and dca<0.015 and cospD > 0.999


XGBOOST_PARAMS:
  # general parameters
  silent: 1 # print message (useful to understand whats happening)
  n_jobs: 8 # number of available threads
  # learning task parameters
  objective: binary:logistic
  random_state: 42
  eval_metric: auc
  tree_method: hist

HYPERPARAMS:
  max_depth: 7
  learning_rate: 0.167
  n_estimators: 83
  gamma: 0.525
  min_child_weight: 9.82
  subsample: 0.89
  colsample_bytree: 0.64
  seed : 42

HYPERPARAMS_RANGE: #TODO: check if it works without tuples
  # booster parameters
  max_depth: !!python/tuple [5, 20] # defines the maximum depth of a single tree (regularization)
  learning_rate: !!python/tuple [0.01, 0.3] # learning rate
  n_estimators: !!python/tuple [50, 500] # number of boosting trees
  gamma: !!python/tuple [0.3, 1.1] # specifies the minimum loss reduction required to make a split
  min_child_weight: !!python/tuple [1, 12]
  subsample: !!python/tuple [0.5, 0.9] # denotes the fraction of observations to be randomly samples for each tree
  colsample_bytree: !!python/tuple [0.5, 0.9] # denotes the fraction of columns to be randomly samples for each tree
  # # lambda: (0,10]  # L2 regularization term on weights
  # # alpha: (0,10]  # L1 regularization term on weight

TRAINING_COLUMNS: 
  - cosp
  - bxy
  - bxyD
  - dca
  - dcaD
  - dist
